Feat/aggregation
Xuyen21/Programming_semester_2 pull request #6
Opened 2023-05-22 22:36 UTC by Xuyen21

i've added some settings of aggregation and the button which will show then an image of word clouds :)

2023-05-22 22:40 UTC, Xuyen21 commented on app/assets/word_clouds.png
should I include also the source code for this image or is ok without it?

2023-05-23 15:04 UTC, SilvanW commented on app/pages/aggres/aggregation.py
> +setting = dbc.CardBody(children=[
Please use an HTML Div instead of a CardBody, so the alignment is the same as in the Filter card.
`setting = html.Div([
    dbc.Row([
        html.P(f'top popularity'),
    dcc.Slider(5, 20, 5, value=10, id='top_popularity_slider'),
    # allow user to slide the popularity range, default value is top 10
    dcc.Dropdown(['bar chart', 'pie chart'], placeholder='choose your preferable chart', value='bar chart',
                 style={'margin-top': 10},
                 id='chart_type'),  # different type of charts,  style={'margin-left': 5, "width": "18rem"},
    ])
])`

2023-05-23 15:07 UTC, SilvanW commented on app/pages/aggres/aggregation.py
> +            dbc.Button('See top words in titles', id='word_clouds_btn', n_clicks=0, color="info",
I find this feature cool - but I'm not sure if we should use a new tab for that (I would suggest we discuss this tomorrow)

2023-05-23 15:08 UTC, SilvanW commented on app/pages/aggres/aggregation.py
> +    html.P(f'top popularity'),
Please write Top popularity (Fit's better into the Layout of the Dashboard)

2023-05-23 15:12 UTC, SilvanW requested changes
Please address the comments I've made. Looking good Otherwise.

2023-05-23 15:26 UTC, KarolinaT92 commented on app/assets/word_clouds.png
Looks cool!

2023-05-23 15:29 UTC, SilvanW commented on app/assets/word_clouds.png
Not sure. If we need to recalculate it then yes otherwise no. The Image feels quite weird because you can't recompute it dynamically.

2023-05-23 15:30 UTC, KarolinaT92 approved these changes

2023-05-23 15:30 UTC, KarolinaT92 approved these changes

2023-05-23 15:30 UTC, KarolinaT92 approved these changes

2023-05-23 15:30 UTC, KarolinaT92 approved these changes

2023-05-23 15:30 UTC, KarolinaT92 approved these changes

2023-05-23 15:30 UTC, KarolinaT92 approved these changes

2023-05-23 16:15 UTC, Xuyen21 commented on app/pages/aggres/aggregation.py
> +            dbc.Button('See top words in titles', id='word_clouds_btn', n_clicks=0, color="info",
i'm also not sure if it's neccessary, i did that just to look as if we have many features, haha. Yah, let's discuss tomorrow

2023-05-23 16:22 UTC, Xuyen21 commented on app/assets/word_clouds.png
ok,then we dont need the code. The image would be better if it can be zoomed in and out. but don't know how :)

2023-05-23 19:09 UTC, SilvanW approved these changes
Looking good

2023-05-23 19:10 UTC, merged